# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 076ecccf9f7147b1420f76ec8d2af568372ac62fa7ffe69ce2e48d2a56fa07d32f515fad62e6ed49dd6ac9c8d5edb13a371ef5210773a14041ac01219df4918c

test:
  secret_key_base: d4aeeaf29b46cac0135d02ac436afec28e8c477e4db2964ec199f2883c1f3c6febb7110befdb357e88cb2eb5dd8491e250f599e5aa211b7788fb69c90bf6257a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
